spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog-master.xml

app:
  jwt:
    secret: SomeRandomSecretKeyThatIsHopefullyLongEnough
    accessToken:
      expiresMin: 60
    refreshToken:
      expiresMin: 120